---

name: Deploy to Kubernetes via GitOps

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set Image Tag
        id: tag
        run: |
          TAG="${GITHUB_SHA::7}"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "Building image with tag: ${TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push image
      - name: Build and push Docker image
        run: |
          docker build -t dhananjaylakkawar/heroku-alike:${{ steps.tag.outputs.TAG }} .
          docker push dhananjaylakkawar/heroku-alike:${{ steps.tag.outputs.TAG }}

      - name: Clone GitOps Repo and Update Tag
        run: |
          git config --global user.email "lakkawardhananjay@gmail.com"
          git config --global user.name "lakkawardhananjay"
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/lakkawardhananjay/helm-argo-kpaas.git
          cd helm-argo-kpaas/

          # Update image tag
          sed -i 's/tag: ".*"/tag: "${{ steps.tag.outputs.TAG }}"/' values.yaml
          
          # Commit changes
          git add values.yaml
          git commit -m "🚀 Auto-update image to ${IMAGE_TAG} from CI"
          git push

          echo "✅ GitOps repository updated successfully!"
